version: '3.7'

services:
  battery-simulator:
    container_name: pybamm-api
    image: batterysimulator:latest
    build:
      context: ./BatterySimulator
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    volumes:
      - ./BatterySimulator:/app
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8084", "--reload" ]
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}

  celery:
    container_name: celery-worker
    build:
      context: ./BatterySimulator
      dockerfile: Dockerfile
    volumes:
      - ./BatterySimulator:/app
    command: [ "celery", "-A", "App.API.tasks:celery", "worker", "--loglevel=info" ]
    environment:
      - CELERY_BROKER_URL=${RABBITMQ_URL}
      - CELERY_RESULT_BACKEND=${REDIS_URL}
    depends_on:
      - rabbitmq
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./BatterySimulator/config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  fastapi_app:
    container_name: webhook
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    volumes:
      - ./Server:/app
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8085", "--reload" ]

volumes:
  redis-data:
