version: '3.7'

services:
  battery-simulator:
    container_name: battery-simulator
    image: batterysimulator:latest
    build:
      context: ./BatterySimulator
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    volumes:
      - ./BatterySimulator:/app
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8084", "--reload" ]
