version: '3.7'

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - battery_simulator_network
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=simulationDB

  battery_simulator:
    container_name: batterySimulationAPI
    image: batterysimulator:latest
    build:
      context: ./BatterySimulator
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    volumes:
      - ./BatterySimulator:/app
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8084", "--reload" ]
    networks:
      - battery_simulator_network

  celery:
    container_name: celeryWorker
    build:
      context: ./BatterySimulator
      dockerfile: Dockerfile
    volumes:
      - ./BatterySimulator:/app
    command: [ "celery", "-A", "App.API.tasks:celery", "worker", "--loglevel=info" ]
    environment:
      - BROKER_URL=redis://redis:6379/0 
      - RESULT_BACKEND=redis://redis:6379/0  
    depends_on:
      - battery_simulator
      - redis 
    networks:
      - battery_simulator_network

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379" 
    networks:
      - battery_simulator_network

volumes:
  mongodb_data:

networks:
  battery_simulator_network:
    driver: bridge
    name: battery_simulator_network
