version: '3.7'

services:
  battery-simulator:
    container_name: pybamm-api
    image: batterysimulator:latest
    build:
      context: ./BatterySimulator
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    volumes:
      - ./BatterySimulator:/app
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8084", "--reload" ]
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}
    networks:
      - network

  celery:
    container_name: celery-worker
    build:
      context: ./BatterySimulator
      dockerfile: Dockerfile
    volumes:
      - ./BatterySimulator:/app
    command: [ "celery", "-A", "App.API.tasks:celery", "worker", "--loglevel=info" ]
    environment:
      - BROKER_URL=${RABBITMQ_URL}
    depends_on:
      - battery-simulator
    networks:
      - network

  fastapi_app:
    container_name: webhook
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    volumes:
      - ./Server:/app
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8085", "--reload" ]
    networks:
      - network

networks:
  network:
