version: '3.7'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - battery_simulator_network
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  battery_simulator:
    container_name: batterySimulationAPI
    image: batterysimulator:latest
    build:
      context: ./BatterySimulator
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    volumes:
      - ./BatterySimulator:/app
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8084", "--reload" ]
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    networks:
      - battery_simulator_network

  celery:
    container_name: celeryWorker
    build:
      context: ./BatterySimulator
      dockerfile: Dockerfile
    volumes:
      - ./BatterySimulator:/app
    command: [ "celery", "-A", "App.API.tasks:celery", "worker", "--loglevel=info" ]
    environment:
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - battery_simulator
      - rabbitmq
    networks:
      - battery_simulator_network

  simulation_notification:
    container_name: simulationNotificationService
    image: simulation_notification_service:latest
    depends_on:
      - celery
    ports:
      - "8082:8082"
    networks:
      - battery_simulator_network

  simulation_manager:
    container_name: simulationManager
    image: simulation_manager:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - producer.enabled=true
    networks:
      - battery_simulator_network
    depends_on:
      - rabbitmq

networks:
  battery_simulator_network:
    driver: bridge
    name: battery_simulator_network
