version: '3.7'

services:
  battery_simulator:
    container_name: batterySimulationAPI
    image: batterysimulator:latest
    build:
      context: ./BatterySimulator
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    volumes:
      - ./BatterySimulator:/app
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8084", "--reload" ]
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}
    networks:
      - battery_simulator_network

  celery:
    container_name: celeryWorker
    build:
      context: ./BatterySimulator
      dockerfile: Dockerfile
    volumes:
      - ./BatterySimulator:/app
    command: [ "celery", "-A", "App.API.tasks:celery", "worker", "--loglevel=info" ]
    environment:
      - BROKER_URL=${RABBITMQ_URL}
    depends_on:
      - battery_simulator
    networks:
      - battery_simulator_network

  simulation_notification:
    container_name: simulationNotificationService
    image: simulation_notification_service:latest
    depends_on:
      - celery
    ports:
      - "8082:8082"
    networks:
      - battery_simulator_network

networks:
  battery_simulator_network:
    driver: bridge
    name: battery_simulator_network
